import {
  author1,
  author2,
  author3,
  author4,
  author5,
  author6,
  author7,
  author8,
  programmingImg,
  articleImg1,
  articleImg2,
  articleImg3,
  articleImg4,
  lifestyleImg,
  abstractImg,
  travelImg,
} from "@/components/assets";
import {
  Camera,
  Car,
  CarIcon,
  Code,
  CookingPot,
  Dog,
  Music,
  Volleyball,
} from "lucide-react";

export const articleData = [
  {
    id: "1",
    title: "UI Interactions of the week #261",
    author: "Joinh Davide",
    date: "May 20, 2021",
    readTime: "3",
    loveCount: "233",
    commentCount: "112",
    authorImageSrc: author1,
    articleHero: articleImg1,
  },
  {
    id: "2",
    title: "UI Interactions of the week #262",
    author: "Jane Doe",
    date: "June 21, 2021",
    readTime: "6",
    loveCount: "23",
    commentCount: "21",
    authorImageSrc: author2,
    articleHero: articleImg2,
  },
  {
    id: "3",
    title: "UI Interactions of the week #263",
    author: "Winston Churchill",
    date: "May 22, 2021",
    readTime: "4",
    loveCount: "33",
    commentCount: "12",
    authorImageSrc: author3,
    articleHero: articleImg3,
  },
  {
    id: "4",
    title: "UI Interactions of the week #264",
    author: "Gates Riley",
    date: "April 10, 2021",
    readTime: "3",
    loveCount: "331",
    commentCount: "192",
    authorImageSrc: author4,
    articleHero: articleImg4,
  },
  {
    id: "5",
    title: "UI Interactions of the week #265",
    author: "Kennedy John",
    date: "May 28, 2021",
    readTime: "9",
    loveCount: "236",
    commentCount: "212",
    authorImageSrc: author5,
    articleHero: programmingImg,
  },
  {
    id: "6",
    title: "UI Interactions of the week #266",
    author: "Kendrick Lamar",
    date: "June 11, 2021",
    readTime: "2",
    loveCount: "103",
    commentCount: "201",
    authorImageSrc: author6,
    articleHero: lifestyleImg,
  },
  {
    id: "7",
    title: "UI Interactions of the week #267",
    author: "John Doe",
    date: "May 31, 2021",
    readTime: "8",
    loveCount: "233",
    commentCount: "112",
    authorImageSrc: author7,
    articleHero: abstractImg,
  },
  {
    id: "8",
    title: "UI Interactions of the week #269",
    author: "Kira Knightley",
    date: "August 22, 2021",
    readTime: "3",
    loveCount: "193",
    commentCount: "82",
    authorImageSrc: author8,
    articleHero: travelImg,
  },
  {
    id: "9",
    title: "UI Interactions of the week #261",
    author: "Joinh Davide",
    date: "May 20, 2021",
    readTime: "3",
    loveCount: "233",
    commentCount: "112",
    authorImageSrc: author1,
    articleHero: articleImg1,
  },
];

export const exploreAuthors = [
  {
    id: "1",
    name: "Ha Noi",
    email: "noi@sade_blog.com",
    followers: "1156",
    authorImageSrc: author1,
    authorHero: articleImg1,
  },
  {
    id: "2",
    name: "Jonathan Giggs",
    email: "jon@sade_blog.com",
    followers: "126",
    authorImageSrc: author2,
    authorHero: articleImg2,
  },
  {
    id: "3",
    name: "Ryan Gosling",
    email: "ryan@sade_blog.com",
    followers: "154",
    authorImageSrc: author3,
    authorHero: articleImg3,
  },
  {
    id: "4",
    name: "Leonardo Doe",
    email: "leo@sade_blog.com",
    followers: "1068",
    authorImageSrc: author4,
    authorHero: articleImg4,
  },
  {
    id: "5",
    name: "Mauki Kenan",
    email: "ken@sade_blog.com",
    followers: "231",
    authorImageSrc: author5,
    authorHero: programmingImg,
  },
  {
    id: "6",
    name: "Sheila Kumar",
    email: "Sheila@sade_blog.com",
    followers: "826",
    authorImageSrc: author6,
    authorHero: lifestyleImg,
  },
  {
    id: "7",
    name: "Candice Parker",
    email: "candy@sade_blog.com",
    followers: "113",
    authorImageSrc: author8,
    authorHero: abstractImg,
  },
];

export const discoverCategories = [
  {
    id: "1",
    name: "Programming",
    icon: Code,
    count: "15",
  },
  {
    id: "2",
    name: "Cars",
    icon: Car,
    count: "11",
  },
  {
    id: "3",
    name: "Animals",
    icon: Dog,
    count: "19",
  },
  {
    id: "4",
    name: "Cooking",
    icon: CookingPot,
    count: "18",
  },
  {
    id: "5",
    name: "Sports",
    icon: Volleyball,
    count: "21",
  },
  {
    id: "6",
    name: "Music",
    icon: Music,
    count: "16",
  },
  {
    id: "7",
    name: "Movies",
    icon: Camera,
    count: "15",
  },
  {
    id: "8",
    name: "Travels",
    icon: CarIcon,
    count: "25",
  },
];

export const exploreTags = [
  {
    id: "1",
    tag: "Ha Noi",
    count: "1123",
    imgSrc: programmingImg,
  },
  {
    id: "2",
    tag: "Hanolulu",
    count: "128",
    imgSrc: lifestyleImg,
  },
  {
    id: "3",
    tag: "Northumbria",
    count: "1123",
    imgSrc: abstractImg,
  },
  {
    id: "4",
    tag: "Kingston",
    count: "513",
    imgSrc: travelImg,
  },
  {
    id: "5",
    tag: "Santa Cruz",
    count: "439",
    imgSrc: lifestyleImg,
  },
  {
    id: "6",
    tag: "Gudalajara",
    count: "1282",
    imgSrc: travelImg,
  },
  {
    id: "7",
    tag: "San Francisco",
    count: "1390",
    imgSrc: programmingImg,
  },
];
